# Generated by Django 5.0.7 on 2025-06-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_alter_students_address_alter_students_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='student_profile_pics/'),
        ),
    ]
